import uuid
from fastapi import APIRouter, Depends
from app.auth.store import get_current_user
from app.models.schemas import ReportRequest, ReportResponse

router = APIRouter(tags=["report"])

@router.post("/", response_model=ReportResponse)
def create_report(
    request: ReportRequest,
    user: dict = Depends(get_current_user)
):
    report_id = str(uuid.uuid4())
    preview = f"Report generated for {request.title}."
    return ReportResponse(report_id=report_id, status="created", preview=preview)

@router.get("/{report_id}")
def get_report(
    report_id: str,
    user: dict = Depends(get_current_user)
):
    return {
        "report_id": report_id,
        "title": "Generated report",
        "content": "This is a placeholder report generated by the export agent.",
    }
